final_conditions = [[1, 13], [2, 12], [3, 15]]
r0 = [1, 4, 13, 12, 15]
s0 = [5, 8, 14]
sF = [13, 12, 15]
shapes = [[1, 1], [1, 1], [1, 1]]
initial_conditions = [[1, 5], [2, 8], [3, 14]]

[[operations]]
pre = [[1, 13], [2, 12]]
post = [[3, 14]]
station_id = -1
id = 21
dt = 0
[[operations]]
pre = [[3, 15]]
post = []
station_id = -1
id = 22
dt = 0
