final_conditions = [[1, 7], [2, 8], [3, 9], [4, 10], [5, 11], [6, 12]]
r0 = [13, 14, 15, 16]
s0 = [1, 2, 3, 4, 5, 6]
sF = [7, 8, 9, 10, 11, 12]
initial_conditions = [[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6]]

[[operations]]
pre = [[2, 8]]
post = [[3, 3]]
"Δt" = 0
[[operations]]
pre = [[1, 7]]
post = [[2, 2]]
"Δt" = 0
[[operations]]
pre = [[3, 9]]
post = []
"Δt" = 0
[[operations]]
pre = [[8, 14]]
post = [[9, 9]]
"Δt" = 0
[[operations]]
pre = [[7, 13]]
post = [[8, 8]]
"Δt" = 0
[[operations]]
pre = [[9, 15]]
post = []
"Δt" = 0
