valid_flag = true
time = 0.020103198
num_A_star_iterations = 0
num_assignment_iterations = 0
num_conflicts = 0
total_A_star_iterations = 552
max_CBS_iterations = 0
LIMIT_assignment_iterations = 50
l3_verbosity = 1
time_limit = 25.0
max_A_star_iterations = 45
LIMIT_A_star_iterations = 8000
l4_verbosity = 0
total_assignment_iterations = 0
l2_verbosity = 2
num_CBS_iterations = 0
l1_verbosity = 2
LIMIT_CBS_iterations = 100
best_cost = [-1, -1, -1, -1]
total_CBS_iterations = 0
DEBUG = false
cost = [67.0, 0.0, 100.0, 0.0, -268.0]
verbosity = 0
