final_conditions = [[1, 8], [2, 10], [3, 12]]
t_request = 20
r0 = []
s0 = [7, 9, 11]
sF = [8, 10, 12]
t_arrival = 20
shapes = [[1, 1], [1, 1], [1, 1]]
initial_conditions = [[1, 7], [2, 9], [3, 11]]

[[operations]]
pre = [[1, 8], [2, 10]]
post = [[3, 11]]
station_id = -1
id = 123
dt = 0
[[operations]]
pre = [[3, 12]]
post = []
station_id = -1
id = 124
dt = 0
