final_conditions = [[1, 383], [2, 476]]
r0 = [472, 441, 517, 4]
s0 = [550, 118]
sF = [383, 476]
shapes = [[1, 1], [1, 2]]
initial_conditions = [[1, 550], [2, 118]]

[[operations]]
pre = [[1, 383]]
post = [[2, 118]]
station_id = 2
id = 15272
dt = 0
[[operations]]
pre = [[2, 476]]
post = []
station_id = -1
id = 15273
dt = 0
