final_conditions = [[1, 259], [2, 405], [3, 230]]
r0 = [590, 493, 113, 28]
s0 = [63, 215, 373]
sF = [259, 405, 230]
shapes = [[1, 1], [1, 2], [2, 1]]
initial_conditions = [[1, 63], [2, 215], [3, 373]]

[[operations]]
pre = [[2, 405]]
post = [[3, 373]]
station_id = 3
id = 15274
dt = 0
[[operations]]
pre = [[1, 259]]
post = [[2, 215]]
station_id = 2
id = 15275
dt = 0
[[operations]]
pre = [[3, 230]]
post = []
station_id = -1
id = 15276
dt = 0
