final_conditions = [[1, 196], [2, 510], [3, 362], [4, 557]]
r0 = [586, 577, 406, 55]
s0 = [509, 380, 104, 130]
sF = [196, 510, 362, 557]
shapes = [[2, 1], [2, 2], [1, 2], [1, 1]]
initial_conditions = [[1, 509], [2, 380], [3, 104], [4, 130]]

[[operations]]
pre = [[3, 362]]
post = [[4, 130]]
station_id = 4
id = 15286
dt = 0
[[operations]]
pre = [[2, 510]]
post = [[3, 104]]
station_id = 3
id = 15287
dt = 0
[[operations]]
pre = [[1, 196]]
post = [[2, 380]]
station_id = 2
id = 15288
dt = 0
[[operations]]
pre = [[4, 557]]
post = []
station_id = -1
id = 15289
dt = 0
