final_conditions = [[1, 476], [2, 488], [3, 336], [4, 107]]
r0 = [147, 580, 382, 41]
s0 = [384, 505, 513, 270]
sF = [476, 488, 336, 107]
shapes = [[1, 1], [2, 1], [1, 2], [2, 1]]
initial_conditions = [[1, 384], [2, 505], [3, 513], [4, 270]]

[[operations]]
pre = [[3, 336]]
post = [[4, 270]]
station_id = 4
id = 15277
dt = 0
[[operations]]
pre = [[2, 488]]
post = [[3, 513]]
station_id = 3
id = 15278
dt = 0
[[operations]]
pre = [[1, 476]]
post = [[2, 505]]
station_id = 2
id = 15279
dt = 0
[[operations]]
pre = [[4, 107]]
post = []
station_id = -1
id = 15280
dt = 0
