final_conditions = [[1, 519], [2, 348], [3, 74], [4, 111]]
r0 = [444, 158, 352, 286]
s0 = [410, 398, 270, 528]
sF = [519, 348, 74, 111]
shapes = [[1, 1], [1, 1], [1, 1], [1, 1]]
initial_conditions = [[1, 410], [2, 398], [3, 270], [4, 528]]

[[operations]]
pre = [[3, 74]]
post = [[4, 528]]
station_id = 4
id = 10
dt = 0
[[operations]]
pre = [[1, 519], [2, 348]]
post = [[3, 270]]
station_id = 3
id = 11
dt = 0
[[operations]]
pre = [[4, 111]]
post = []
station_id = -1
id = 12
dt = 0
