valid_flag = true
time = 3.624417258
num_A_star_iterations = 0
num_assignment_iterations = 0
num_conflicts = 0
total_A_star_iterations = 268
max_CBS_iterations = 0
LIMIT_assignment_iterations = 50
l3_verbosity = 1
time_limit = 25.0
max_A_star_iterations = 51
LIMIT_A_star_iterations = 8000
l4_verbosity = 0
total_assignment_iterations = 0
l2_verbosity = 2
num_CBS_iterations = 0
l1_verbosity = 2
LIMIT_CBS_iterations = 100
best_cost = [-1, -1, -1, -1]
total_CBS_iterations = 0
DEBUG = false
cost = [65.0, 0.0, 115.0, 0.0, -260.0]
verbosity = 0
