final_conditions = [[1, 10], [2, 11], [3, 12]]
t_request = 10
r0 = []
s0 = [4, 5, 6]
sF = [10, 11, 12]
t_arrival = 10
shapes = [[1, 1], [1, 1], [1, 1]]
initial_conditions = [[1, 4], [2, 5], [3, 6]]

[[operations]]
pre = [[1, 10], [2, 11]]
post = [[3, 6]]
station_id = -1
id = 26
dt = 0
[[operations]]
pre = [[3, 12]]
post = []
station_id = -1
id = 27
dt = 0
